# desktop
# Detect operating system
UNAME_S := $(shell uname -s)

OPT = -g
CFLAGS = -flto=auto
SDL = SDL2
GL = GL

# Set default PREFIX values if not set
PREFIX ?= /usr
PREFIX_LOCAL ?= $(HOME)/.local

# legacy linux paths
CFLAGS += -I$(PREFIX)/include -I$(PREFIX_LOCAL)/include
LDFLAGS = -L$(PREFIX)/lib -L$(PREFIX_LOCAL)/lib

# dependencies
CFLAGS += -DUSE_$(SDL)
LDFLAGS += -lpthread -ldl -lm -lz

# platform dependencies
ifeq ($(UNAME_S),Linux)
    # pkg-config
    CFLAGS += `pkg-config --cflags sdl2`
    LDFLAGS += `pkg-config --libs sdl2`
    # SDL2_image and SDL2_ttf are optional - only link if available
    ifeq ($(shell pkg-config --exists SDL2_image && echo yes),yes)
        CFLAGS += `pkg-config --cflags SDL2_image`
        LDFLAGS += `pkg-config --libs SDL2_image`
    else
        # Add stub defines if SDL2_image is not available
        CFLAGS += -DNO_SDL2_IMAGE
    endif
    ifeq ($(shell pkg-config --exists SDL2_ttf && echo yes),yes)
        CFLAGS += `pkg-config --cflags SDL2_ttf`
        LDFLAGS += `pkg-config --libs SDL2_ttf`
    else
        # Add stub defines if SDL2_ttf is not available
        CFLAGS += -DNO_SDL2_TTF
    endif
    # opengl
    CFLAGS += -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
    LDFLAGS += `pkg-config --libs gl` `pkg-config --libs glesv2`
    # silence some warnings for now, we'll sort those later
    CFLAGS += -Wno-format-overflow -Wno-format-truncation -Wno-format-zero-length -Wno-format-extra-args -Wno-format
endif

ifeq ($(UNAME_S),Darwin)
    # sdl
    LDFLAGS += -l$(SDL) -l$(SDL)_image -l$(SDL)_ttf
    # opengl
    CFLAGS += -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
    LDFLAGS += -framework OpenGL
    # sqlite
    CFLAGS += -I/opt/homebrew/opt/sqlite/include
    LDFLAGS += -L/opt/homebrew/opt/sqlite/lib
endif

# we have some super old opengl code that throws warnings a lot
CFLAGS += -DGL_SILENCE_DEPRECATION
# TODO: this shouldnt be necessary.
# move resampling code out of api.c
LDFLAGS += -lsamplerate