$(PLATFORM):
	# $@
	# Build minarch (required by system target)
	(cd ./workspace/all/minarch && make PLATFORM=$(PLATFORM))
	# Build nextval (required by system target)
	(cd ./workspace/all/nextval && make PLATFORM=$(PLATFORM))
	# Build nextui
	(cd ./workspace/all/nextui && make PLATFORM=$(PLATFORM))
